name: Run Pytest and Upload Code Coverage

on:
  workflow_dispatch:
  workflow_call:

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ "3.10", "3.11", "3.12", "3.13" ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup UV package manager
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python }}
          version: "latest"

      - name: Run commands
        run: |
          uv sync --group develop --frozen
          pytest --cov-report=xml

      - name: Upload codecov artifact
        if: ${{ matrix.python == '3.13' }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./coverage.xml

  codecov:
    needs: pytest
    runs-on: ubuntu-latest
    steps:
      - name: Download codecov artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-report

      - name: Upload code coverage
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
